global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quantix-devnet'
    static_configs:
      - targets: ['quantix-devnet:8560']
        labels:
          env: devnet
          node: devnet

  - job_name: 'quantix-testnet'
    static_configs:
      - targets:
          - 'validator-0:8560'
          - 'validator-1:8561'
          - 'validator-2:8562'
          - 'validator-3:8563'
        labels:
          env: testnet
    relabel_configs:
      - source_labels: [__address__]
        target_label: node
        regex: '([^:]+):.*'
        replacement: '$1'
