global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Devnet single node
  - job_name: 'quantix-devnet'
    static_configs:
      - targets: ['quantix-devnet:8560']
        labels:
          env: 'devnet'
          node: 'node0'

  # Testnet 4 nodes
  - job_name: 'quantix-testnet'
    static_configs:
      - targets:
          - 'node0:8560'
          - 'node1:8561'
          - 'node2:8562'
          - 'node3:8563'
        labels:
          env: 'testnet'
    relabel_configs:
      - source_labels: [__address__]
        target_label: node
        regex: '([^:]+):.*'
        replacement: '$1'
